// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrqueitxgbgeybclhamn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycXVlaXR4Z2JnZXliY2xoYW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MjQ4NjcsImV4cCI6MjA5NjAwMDg2N30.nGXs35_YC3Xa3PHyhX5OUp_MaNo9gz2NpONMAdc3frI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});